### ISSUE TITLE
import from 1password error.

### ISSUE THREAD

**Issue by peacetara** [jcs/bitwarden-ruby#15]
tools/1password_import.rb:153:in `block in <main>': unimplemented: "system.folder.SavedSearch" (RuntimeError)
	from tools/1password_import.rb:85:in `each'
	from tools/1password_import.rb:85:in `<main>'

**Comment by peacetara** [comment]
Erasing the smart folders inside 1Password and then re-creating the .1pif seems to fix this error.

**Comment by peacetara** [comment]
these 2 also need to be added to ignore:

"wallet.financial.BankAccountUS",
 "wallet.government.SsnUS"
