### ISSUE TITLE
undefined method `try`

### ISSUE THREAD

**Issue by papertigers** [jcs/bitwarden-ruby#56]
Have you seen the following error before?  Not sure what changed, I tried to upgrade to the latest in master with the sinatra fix.

```
2018-06-28 17:19:36 - NoMethodError - undefined method `try' for #<Hash:0x00000000005cabe8>:
        /home/warden/src/bitwarden-ruby/lib/dbmodel.rb:65:in `fetch_columns'
        /home/warden/src/bitwarden-ruby/lib/dbmodel.rb:88:in `find_all_by_column'
        /home/warden/src/bitwarden-ruby/lib/dbmodel.rb:104:in `find_by_column'
        /home/warden/src/bitwarden-ruby/lib/dbmodel.rb:23:in `method_missing'
        /home/warden/src/bitwarden-ruby/lib/routes/identity.rb:35:in `block (2 levels) in registered'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1635:in `call'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1635:in `block in compile!'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:992:in `block (3 levels) in route!'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1011:in `route_eval'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:992:in `block (2 levels) in route!'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1040:in `block in process_route'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1038:in `catch'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1038:in `process_route'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:990:in `block in route!'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:989:in `each'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:989:in `route!'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1097:in `block in dispatch!'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `block in invoke'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `catch'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `invoke'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1094:in `dispatch!'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:924:in `block in call!'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `block in invoke'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `catch'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1076:in `invoke'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:924:in `call!'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:913:in `call'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.3/lib/rack/protection/xss_header.rb:18:in `call'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.3/lib/rack/protection/json_csrf.rb:26:in `call'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.3/lib/rack/protection/base.rb:50:in `call'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.3/lib/rack/protection/base.rb:50:in `call'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/rack-protection-2.0.3/lib/rack/protection/frame_options.rb:31:in `call'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/logger.rb:15:in `call'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/common_logger.rb:33:in `call'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:231:in `call'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:224:in `call'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:194:in `call'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1958:in `call'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1502:in `block in call'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1729:in `synchronize'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.3/lib/sinatra/base.rb:1502:in `call'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.1/lib/unicorn/http_server.rb:606:in `process_client'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.1/lib/unicorn/http_server.rb:702:in `worker_loop'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.1/lib/unicorn/http_server.rb:549:in `spawn_missing_workers'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.1/lib/unicorn/http_server.rb:142:in `start'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/gems/unicorn-5.3.1/bin/unicorn:126:in `<top (required)>'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/bin/unicorn:23:in `load'
        /home/warden/src/bitwarden-ruby/vendor/bundle/ruby/2.4.0/bin/unicorn:23:in `<main>'
10.0.1.200 - - [28/Jun/2018:17:19:36 +0000] "POST /identity/connect/token HTTP/1.1" 500 30 0.0091
```

**Comment by papertigers** [comment]
Running `git checkout 2231d81a25d702a50835b9211467884eacceabc7` does make things work again fwiw.  So, perhaps `663da6` doesn't fix the error you were attempting to fix?

**Comment by papertigers** [comment]
Fix confirmed.  Thanks!
